'use client';
import {useId,useRef,useState} from 'react';
import type {CollectionRequest,SharedCollection,SharedEntry} from '@/lib/collections';
import {splitTags} from '@/lib/collections';
import {Spinner} from '../dashboard/loading';
export function EntryForm({collection,request,done,initial}:{collection:SharedCollection;request:CollectionRequest;done:()=>void;initial?:{title?:string;url?:string;body?:string;captureId?:string;hasImage?:boolean}}) {
 const id=useId(),clientId=useRef<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const pending=collection.requireApproval&&!collection.canModerate;
 return <form className="collection-form entry-form" aria-label="Add to collection" onChange={()=>{clientId.current=null;setMessage('');}} onSubmit={async event=>{
  event.preventDefault();if(busy)return;const form=event.currentTarget,values=new FormData(form);setBusy(true);setError('');clientId.current||=crypto.randomUUID();
  try{const result=await request<{entry:SharedEntry}>(`/collections/${collection.id}/entries`,{method:'POST',body:{clientId:clientId.current,title:values.get('title'),url:values.get('url'),body:values.get('body'),tags:splitTags(String(values.get('tags')||'')),captureId:initial?.captureId,shareImage:values.get('shareImage')==='on'}});setMessage(result.entry.status==='pending'?'Submitted. The owner or a moderator will approve it before it appears.':'Added to the collection.');clientId.current=null;form.reset();done();}catch(e){setError(e instanceof Error?e.message:'Could not add this find. Please try again.');}finally{setBusy(false);}
 }}><h2>{pending?'Suggest a find':'Add a find'}</h2><p>Share a link, a useful quote, or a note. Only the content in this form is shared.</p><fieldset disabled={busy}><label htmlFor={id+'title'}>Title</label><input id={id+'title'} name="title" required maxLength={200} defaultValue={initial?.title||''} placeholder="What makes this worth keeping?"/><label htmlFor={id+'url'}>Source link <span>(optional)</span></label><input id={id+'url'} name="url" type="url" maxLength={2048} defaultValue={initial?.url||''} placeholder="https://…"/><label htmlFor={id+'body'}>Description or quote <span>(optional)</span></label><textarea id={id+'body'} name="body" maxLength={5000} rows={4} defaultValue={initial?.body||''} placeholder="Add the part you want to share, or explain why it is useful."/><label htmlFor={id+'tags'}>Tags <span>(comma separated, up to 10)</span></label><input id={id+'tags'} name="tags" maxLength={410} placeholder="agents, skills, inspiration"/>{initial?.hasImage?<label className="collection-checkbox"><input type="checkbox" name="shareImage"/>Include the saved image in this collection</label>:null}</fieldset><p className="collection-disclosure">{collection.visibility==='public'?'This collection is public.':'This collection is private.'} The owner controls its visibility. {pending?'Your submission stays in the approval queue until accepted.':'This will appear immediately.'}</p>{error?<p className="collection-error" role="alert">{error}</p>:null}{message?<p className="collection-success" role="status">{message}</p>:null}<button className="button primary" disabled={busy}>{busy?<><Spinner/>Adding…</>:pending?'Submit for approval':'Add to collection'}</button></form>;
}
