'use client';
import Link from 'next/link';
import {useRouter,useSearchParams} from 'next/navigation';
import {SegmentedControl} from '../ui/segmented-control';
import {useState} from 'react';
import {useInfiniteQuery,useQuery,useQueryClient} from '@tanstack/react-query';
import {useDashboard} from '../dashboard/context';
import {PageHeading} from '../dashboard/page-heading';
import {SectionLoading} from '../dashboard/loading';
import type {CollectionDetail,CollectionList,SharedCollection} from '@/lib/collections';
import {CollectionCard,CollectionRules} from './shared';
import {CollectionForm} from './collection-form';
import {EntryForm} from './entry-form';
import {Entries} from './entries';
import {Members} from './members';
import './collections.css';
export default function Collections({id}:{id?:string}) {
 const {request,toast}=useDashboard(),router=useRouter(),queryClient=useQueryClient();
 const [create,setCreate]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const params=useSearchParams();
 const filter=['all','owned','joined','following'].includes(params.get('filter')||'')?params.get('filter')!:'all';
 const tab=['finds','add','pending','settings','members'].includes(params.get('tab')||'')?params.get('tab')!:'finds';
 const setParam=(name:string,value:string,fallback:string)=>{const next=new URLSearchParams(params.toString());if(value===fallback)next.delete(name);else next.set(name,value);window.history.pushState(null,'',window.location.pathname+(next.size?'?'+next:''));};
 const setFilter=(value:string)=>setParam('filter',value,'all'),setTab=(value:string)=>setParam('tab',value,'finds');
 const list=useQuery({queryKey:['social-collections'],queryFn:({signal})=>request<CollectionList>('/collections',{signal})});
 const detail=useInfiniteQuery({queryKey:['social-collection',id,tab==='pending'],queryFn:({signal,pageParam})=>request<CollectionDetail>(`/collections/${id}?${tab==='pending'?'view=pending&':''}cursor=${pageParam||'0'}`,{signal}),enabled:!!id,initialPageParam:undefined as string|undefined,getNextPageParam:last=>last.nextCursor||undefined});
 const c=detail.data?.pages[0].collection;
 // Finds and the approval queue are cached under separate keys (tab==='pending'),
 // so a mutation must invalidate the whole collection prefix — refetching only the
 // active query leaves the other tab stale past staleTime until a hard reload.
 const refresh=()=>{void queryClient.invalidateQueries({queryKey:['social-collection',id]});void list.refetch();};
 async function invite(collectionId:string,accept:boolean) {setBusy(true);setMessage('');try{await request(`/collections/${collectionId}/invitation`,{method:'POST',body:{accept}});await list.refetch();toast(accept?'You joined the group.':'Invitation declined.');}catch(e){setMessage(e instanceof Error?e.message:'Could not update the invitation.');}finally{setBusy(false);}}
 if(id) {
  if(detail.isPending)return <SectionLoading label="Opening collection…"/>;
  if(detail.isError)return <section className="social-collections"><h1>Collection unavailable</h1><p role="alert">{detail.error.message}</p><button className="button secondary" onClick={()=>void detail.refetch()}>Try again</button><Link href="/dashboard/collections">Back to collections</Link></section>;
  if(!c)return null;
  const entries=detail.data.pages.flatMap(p=>p.entries).filter((entry,index,array)=>array.findIndex(e=>e.id===entry.id)===index);
  return <div className="social-collections"><Link className="text-link" href="/dashboard/collections">Back to collections</Link><PageHeading title={c.title} description={c.description||'A home for the finds worth sharing.'}/><div className="collection-toolbar"><span className="collection-visibility">{c.visibility==='public'?'Public collection':'Private collection'}{c.kind==='group'?' · Group':''}</span><Link className="button secondary" href={`/collection/${c.slug}`} prefetch={false}>Open collection page <span aria-hidden="true">↗</span></Link><button className="subtle-button" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/collection/'+c.slug);toast('Collection link copied.');}catch{setMessage('Copy this address: '+location.origin+'/collection/'+c.slug);}}}>Copy link</button></div><SegmentedControl className="collection-tabs" label="Collection sections" value={tab} items={[["finds",`Finds · ${c.entries}`],...(c.canSubmit?[["add","Add a find"]]:[]),...(c.canModerate?[["pending",`Approval queue · ${detail.data.pages[0].pending}`]]:[]),...(c.role==='owner'?[["settings","Settings"],...(c.kind==='group'?[["members","Members"]]:[])]:[])].map(([value,label])=>({value,label}))} onChange={value=>{setTab(value);setMessage('');}} />{message?<p className="collection-error" role="alert">{message}</p>:null}{tab==='settings'&&c.role==='owner'?<><CollectionForm current={c} request={request} canCreateGroup={list.data?.canCreateGroup||false} done={()=>{refresh();toast('Collection settings saved.');}}/><section className="collection-delete"><h2>Delete this collection</h2><p>This removes the shared page, entries and membership. Private library copies stay.</p><button className="button danger-quiet" disabled={busy} onClick={async()=>{if(!window.confirm('Delete this collection and all its shared entries?'))return;setBusy(true);try{await request(`/collections/${c.id}`,{method:'DELETE'});await queryClient.invalidateQueries({queryKey:['social-collections']});router.push('/dashboard/collections');}catch(e){setMessage(e instanceof Error?e.message:'Could not delete collection.');setBusy(false);}}}>Delete collection</button></section></>:tab==='members'&&c.role==='owner'?<Members collection={c} request={request}/>:tab==='add'&&c.canSubmit?<div className="collection-reading-layout"><EntryForm collection={c} request={request} done={refresh}/><CollectionRules collection={c}/></div>:<><Entries collection={c} entries={entries} request={request} changed={refresh} pendingOnly={tab==='pending'}/>{detail.hasNextPage?<button className="button secondary" disabled={detail.isFetchingNextPage} onClick={()=>void detail.fetchNextPage()}>{detail.isFetchingNextPage?'Loading…':'Load more finds'}</button>:null}</>}</div>;
 }
 return <div className="social-collections"><PageHeading title="Your collections." description="Good finds become better together. Curate a page, invite your people, or follow a collection you love."/><div className="collection-toolbar"><button className="button primary" onClick={()=>setCreate(!create)}>{create?'Close new collection':'New collection'}</button><Link className="button secondary" href="/collections">Explore public collections</Link></div>{create?<CollectionForm request={request} canCreateGroup={list.data?.canCreateGroup||false} done={c=>{void queryClient.invalidateQueries({queryKey:['social-collections']});router.push(`/dashboard/collections/${c.id}`);}}/>:null}{message?<p className="collection-error" role="alert">{message}</p>:null}{list.data?.invitations.length?<section className="collection-invitations"><h2>You’re invited</h2>{list.data.invitations.map(inv=><div key={inv.id}><div><strong>{inv.title}</strong><p>Join as a {inv.role}</p></div><button className="button primary compact" disabled={busy} onClick={()=>void invite(inv.id,true)}>Join group</button><button className="subtle-button" disabled={busy} onClick={()=>void invite(inv.id,false)}>Decline</button></div>)}</section>:null}<SegmentedControl className="collection-tabs" label="Your collection lists" value={filter} items={[["all","All collections"],["owned","Created by you"],["joined","Your groups"],["following","Following"]].map(([value,label])=>({value,label}))} onChange={setFilter} />{list.isPending?<SectionLoading label="Loading collections…"/>:list.isError?<div role="alert"><p>{list.error.message}</p><button className="button secondary" onClick={()=>void list.refetch()}>Try again</button></div>:<CollectionGrid collections={list.data.collections.filter(c=>filter==='owned'?c.role==='owner':filter==='joined'?!!c.role&&c.role!=='owner':filter==='following'?c.following:true)}/>}</div>;
}
function CollectionGrid({collections}:{collections:SharedCollection[]}) {return collections.length?<div className="collection-grid-list">{collections.map(c=><CollectionCard key={c.id} collection={c} manage/>)}</div>:<section className="collection-empty"><svg viewBox="0 0 64 64" aria-hidden="true"><rect x="12" y="18" width="40" height="34" rx="5"/><path d="M19 18v-6h26v6M25 28h14m-7-7v14"/></svg><h2>A collection starts with one good find.</h2><p>Make a reading list, gather your favorite posts, or build a shared library of agents and skills. Personal collections and following are free.</p></section>;}
