'use client';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import type {CollectionRequest,SharedCollection} from '@/lib/collections';
type Member={id:string;name:string;email:string;role:string;accepted:number};
export function Members({collection,request}:{collection:SharedCollection;request:CollectionRequest}) {
 const query=useQuery({queryKey:['collection-members',collection.id],queryFn:({signal})=>request<{members:Member[]}>(`/collections/${collection.id}/members`,{signal})});
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 return <section className="collection-members"><h2>Collect together</h2><p>Invite someone with a Foundkeep account. They can accept from their Collections page.</p><form className="collection-form" onSubmit={async event=>{event.preventDefault();if(busy)return;const form=event.currentTarget,f=new FormData(form);setBusy(true);setError('');try{await request(`/collections/${collection.id}/members`,{method:'POST',body:{email:f.get('email'),role:f.get('role')}});form.reset();await query.refetch();}catch(e){setError(e instanceof Error?e.message:'Could not invite this person.');}finally{setBusy(false);}}}><fieldset disabled={busy}><label htmlFor="member-email">Foundkeep account email</label><input id="member-email" name="email" type="email" required maxLength={254} placeholder="friend@example.com"/><label htmlFor="member-role">Role</label><select id="member-role" name="role"><option value="contributor">Contributor · add finds</option><option value="moderator">Moderator · publish and approve finds</option><option value="viewer">Viewer · read only</option></select></fieldset><button className="button primary" disabled={busy}>{busy?'Inviting…':'Invite to group'}</button></form>{error?<p role="alert" className="collection-error">{error}</p>:null}{query.isError?<p role="alert">Could not load members. <button onClick={()=>void query.refetch()}>Try again</button></p>:query.isPending?<p role="status">Loading members…</p>:<ul>{query.data.members.map(member=><li key={member.id}><div><strong>{member.name}</strong><span>{member.email}</span><small>{member.role} · {member.accepted?'Joined':'Invitation pending'}</small></div><button className="subtle-button" disabled={busy} onClick={async()=>{if(!window.confirm(`Remove ${member.name} from this group?`))return;setBusy(true);setError('');try{await request(`/collections/${collection.id}/members/${member.id}`,{method:'DELETE'});await query.refetch();}catch(e){setError(e instanceof Error?e.message:'Could not remove this member.');}finally{setBusy(false);}}}>Remove</button></li>)}</ul>}<p className="field-help">To change a member’s role, enter their email and choose the new role above.</p></section>;
}
