import Link from 'next/link';
import type {Metadata} from 'next';
import {serverApi} from '@/lib/server';
import type {SharedCollection} from '@/lib/collections';
import {CollectionCard} from '@/components/collections/shared';
import '../customer.css';
import '@/components/collections/collections.css';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Explore public collections',description:'Discover useful links, ideas, agents and skills, curated by people on Foundkeep.',alternates:{canonical:'/collections'},robots:{index:true,follow:true}};
export default async function CollectionsDirectory({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {const query=await searchParams,q=typeof query.q==='string'?query.q.slice(0,100):'',cursor=typeof query.cursor==='string'&&/^\d{1,6}$/.test(query.cursor)?query.cursor:'0';const data=await serverApi<{collections:SharedCollection[];nextCursor:string|null}>('/public/collections?'+new URLSearchParams({q,cursor}));return <div className="social-collections public-collections-shell"><header className="public-collection-nav"><Link className="brand" href="/"><img src="/assets/studio-mark.svg?v=bookmark-evolved-1" alt="" width={32} height={32}/>Foundkeep</Link><Link href="/dashboard/collections">My collections</Link></header><main className="public-collection"><header className="public-collection-heading directory-heading"><h1>Good finds.<br/>Better together.</h1><p>Explore what people are keeping. Follow a collection, find your next useful idea, or start one of your own.</p><form className="collection-search" action="/collections"><label className="sr-only" htmlFor="collection-search">Search public collections</label><input id="collection-search" name="q" type="search" maxLength={100} defaultValue={q} placeholder="Search agents, skills, design…"/><button className="button primary">Search</button></form></header><div className="collection-directory-heading"><h2>{q?`Collections for “${q}”`:'Recently curated'}</h2><Link href="/dashboard/collections">Create a collection</Link></div>{data.collections.length?<div className="collection-grid-list">{data.collections.map(c=><CollectionCard key={c.id} collection={c}/>)}</div>:<section className="collection-empty"><h2>{q?'No collections match yet.':'The first collection could be yours.'}</h2><p>{q?'Try a different topic, or make a collection for it.':'Gather the links and ideas you keep recommending, and give them a public home.'}</p><Link className="button primary" href="/dashboard/collections">Start a collection</Link></section>}{data.nextCursor?<Link className="button secondary" href={'/collections?'+new URLSearchParams({q,cursor:data.nextCursor})}>More collections</Link>:null}</main></div>;}
