import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright-core';

const base = process.env.BASE_URL || 'http://127.0.0.1:18791';
assert.ok(['127.0.0.1', 'localhost'].includes(new URL(base).hostname), 'Use a disposable local backend.');

test('Library first uses real collections, logo reopening, and an accessible mobile drawer', async t => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH, args: ['--no-sandbox'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'no-preference' });
  const password = 'Sidebar-disposable-719386-QA'; let account;
  t.after(async () => { try { if (account) assert.equal((await context.request.delete(base + '/api/account', { headers: { Origin: base, 'X-Atlas-Account': account.id }, data: { password } })).status(), 200); } finally { await browser.close(); } });
  const registration = await context.request.post(base + '/api/auth/register', { headers: { Origin: base }, data: { email: `sidebar-${crypto.randomUUID()}@example.test`, name: 'Sidebar collector', password } });
  assert.equal(registration.status(), 201, await registration.text()); account = (await registration.json()).account;
  const headers = { Origin: base, 'X-Atlas-Account': account.id };
  const created = await context.request.post(base + '/api/collections', { headers, data: { title: 'Design inspiration from my private library', slug: 'sidebar-' + crypto.randomUUID(), visibility: 'private', kind: 'personal' } });
  assert.equal(created.status(), 201, await created.text()); const collection = (await created.json()).collection;
  const savedResponse = await context.request.post(base + '/api/captures', { headers, data: { clientId: crypto.randomUUID(), type: 'note', noteText: 'A saved idea worth returning to.', capturedAt: Date.now() } });
  assert.equal(savedResponse.status(), 201); const saved = (await savedResponse.json()).capture;
  const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(base + '/dashboard'); await page.locator('#new-note:enabled').waitFor();
  const sidebar = page.locator('.library-sidebar'), toggle = page.locator('#toggle-sidebar'), main = page.locator('#main'), logo = page.locator('#sidebar-logo');
  assert.equal(await logo.locator('.sidebar-wordmark').textContent(), 'FoundKeep');
  assert.ok(parseFloat(await logo.evaluate(el => getComputedStyle(el).fontSize)) <= 18);
  assert.equal(await page.getByRole('button', { name: /workspace/i }).count(), 0);
  const collectionLink = page.locator('.sidebar-collection-link', { hasText: collection.title }); await collectionLink.waitFor();
  assert.equal(await collectionLink.getAttribute('href'), '/dashboard/collections/' + collection.id);
  await collectionLink.click(); await page.waitForURL(base + '/dashboard/collections/' + collection.id);
  await page.getByRole('heading', { name: collection.title, exact: true }).waitFor();
  assert.equal(await page.locator('.sidebar-collection-link[aria-current="page"]').getAttribute('href'), '/dashboard/collections/' + collection.id);
  await page.locator('#open-agents').click(); await page.waitForURL(base + '/dashboard/agents');
  const originalWidth = (await main.boundingBox()).width;
  await toggle.focus(); await page.keyboard.press('Enter');
  await page.waitForFunction(() => document.querySelector('.library-sidebar')?.dataset.collapsed === 'true' && getComputedStyle(document.querySelector('#main')).transform === 'none');
  assert.equal(await toggle.isVisible(), false); assert.equal(await logo.getAttribute('aria-expanded'), 'false');
  assert.equal(await logo.evaluate(el => el === document.activeElement), true);
  assert.ok((await sidebar.boundingBox()).width <= 80); assert.ok((await main.boundingBox()).width > originalWidth + 150);
  await page.reload(); await page.waitForFunction(() => document.querySelector('.library-sidebar')?.dataset.collapsed === 'true');
  await logo.click(); assert.equal(page.url(), base + '/dashboard/agents', 'Logo reopens without changing the page');
  assert.equal(await sidebar.getAttribute('data-collapsed'), 'false');
  assert.equal(await sidebar.getByRole('button', { name: 'New note', exact: true }).count(), 0);
  await page.locator('#all-captures').click(); await page.waitForURL(base + '/dashboard'); await page.locator('#new-note:enabled').click(); await page.waitForURL('**/dashboard?panel=note');
  await page.locator('#note-text').fill('A note from the new sidebar.'); await page.locator('#save-note').click();
  await page.locator('#note-dialog').waitFor({ state: 'hidden' }); await page.getByText('A note from the new sidebar.', { exact: true }).first().waitFor();
  await page.locator('#open-account').click(); await page.waitForURL(base + '/dashboard/settings');
  assert.equal(await page.locator('#sidebar-account-menu, #sidebar-switch-account').count(), 0);
  await page.getByRole('heading', { name: 'Settings', exact: true }).waitFor();
  await mkdir('.impeccable/review/library-first', { recursive: true });
  await page.screenshot({ path: '.impeccable/review/library-first/desktop.png', fullPage: true, animations: 'disabled' });
  await toggle.click(); await page.setViewportSize({ width: 390, height: 844 });
  const open = page.locator('#open-sidebar'); await open.waitFor(); await sidebar.waitFor({ state: 'hidden' });
  assert.equal(await page.locator('.sidebar-mobile-header img,.sidebar-mobile-header .brand').count(), 0);
  assert.equal(await open.locator('svg path').getAttribute('d'), 'M4 7h16M4 12h16M4 17h16');
  await page.screenshot({ path: '.impeccable/review/library-first/phone-closed.png', fullPage: true, animations: 'disabled' });
  await open.click(); await sidebar.waitFor({ state: 'visible' });
  assert.equal(await sidebar.getAttribute('aria-modal'), 'true'); assert.equal(await main.evaluate(el => el.inert), true);
  assert.equal(await open.getAttribute('aria-expanded'), 'true'); assert.equal(await toggle.evaluate(el => el === document.activeElement), true);
  await page.screenshot({ path: '.impeccable/review/library-first/phone-open.png', animations: 'disabled' });
  await logo.focus(); await page.keyboard.press('Shift+Tab'); assert.equal(await page.locator('#open-account').evaluate(el => el === document.activeElement), true);
  await page.keyboard.press('Tab'); assert.equal(await logo.evaluate(el => el === document.activeElement), true);
  await page.keyboard.press('Escape'); assert.equal(await main.evaluate(el => el.inert), false); assert.equal(await open.evaluate(el => el === document.activeElement), true);
  await open.click(); await page.locator('#open-plans').click(); await page.waitForURL(base + '/dashboard/plans'); await sidebar.waitFor({ state: 'hidden' });
  assert.equal(await main.evaluate(el => el.inert), false); assert.equal(await page.evaluate(() => document.body.style.overflow), '');
  await open.click(); await page.locator('.sidebar-backdrop').click({ position: { x: 380, y: 100 } }); await sidebar.waitFor({ state: 'hidden' }); assert.equal(await main.evaluate(el => el.inert), false);
  await open.click(); await toggle.click(); assert.equal(await open.evaluate(el => el === document.activeElement), true);
  for (const width of [320, 390, 760, 820, 1100, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    if (width <= 760) { await open.waitFor(); await open.click(); } else { await page.waitForFunction(() => !document.querySelector('#main').inert); if (await sidebar.getAttribute('data-collapsed') === 'true') await logo.click(); }
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `Fits ${width}px`);
    const bounds = await toggle.boundingBox(); assert.ok(bounds.width >= (width <= 760 ? 44 : 36) && bounds.height >= (width <= 760 ? 44 : 36), JSON.stringify({ width, bounds }));
    if (width <= 760) await toggle.click();
  }
  await page.emulateMedia({ reducedMotion: 'reduce' }); await toggle.click(); assert.equal(await main.evaluate(el => getComputedStyle(el).transform), 'none'); await logo.click();
  await page.setViewportSize({ width: 320, height: 500 }); await open.waitFor(); await open.click();
  const accountBounds = await page.locator('#open-account').boundingBox(); assert.ok(accountBounds.y >= 0 && accountBounds.y + accountBounds.height <= 500);
  await page.locator('#open-account').click(); await page.waitForURL(base + '/dashboard/settings'); await sidebar.waitFor({ state: 'hidden' });
  const privateContext = await browser.newContext({ storageState: await context.storageState(), viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  await privateContext.addInitScript(() => Object.defineProperty(window, 'localStorage', { get() { throw new DOMException('Storage unavailable', 'SecurityError'); } }));
  const privatePage = await privateContext.newPage(); privatePage.on('pageerror', e => errors.push(e.message)); await privatePage.goto(base + '/dashboard'); await privatePage.locator('#toggle-sidebar').click();
  assert.equal(await privatePage.locator('.library-sidebar').getAttribute('data-collapsed'), 'true'); await privatePage.locator('#sidebar-logo').click(); await privateContext.close();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base + '/dashboard/saved/' + saved.id); await page.locator('.capture-reading-view').waitFor();
  await page.locator('#open-sidebar').click(); await page.keyboard.press('Escape');
  await sidebar.waitFor({ state: 'hidden' }); assert.equal(page.url(), base + '/dashboard/saved/' + saved.id, 'Drawer Escape preserves the open reader');
  await page.setViewportSize({ width: 1440, height: 1000 }); await page.locator('#open-account').click(); await page.waitForURL(base + '/dashboard/settings');
  assert.equal(await page.locator('#sidebar-account-menu').count(), 0, 'Account opens settings directly');
  await page.goto(base + '/dashboard?item=' + saved.id); await page.locator('.capture-detail-panel').waitFor();
  for (const width of [761, 820, 1000]) {
    await page.setViewportSize({ width, height: 900 });
    assert.equal(await page.locator('#capture-dialog[open]').count(), 1, 'Tablet reader floats over the retained library');
    assert.ok((await page.locator('.capture-detail-panel').boundingBox()).width >= 400, `Readable panel at ${width}px`);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  }
  await page.getByRole('button', { name: 'Close capture', exact: true }).click(); await page.locator('.capture-card').first().waitFor();
  assert.deepEqual(errors, []);
});

test('sidebar data failures recover honestly and account settings releases the mobile drawer', async t => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH, args: ['--no-sandbox'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const email = `sidebar-menu-${crypto.randomUUID()}@example.test`, password = 'Sidebar-menu-disposable-394275';
  const registration = await context.request.post(base + '/api/auth/register', { headers: { Origin: base }, data: { email, name: 'Account controls', password } });
  assert.equal(registration.status(), 201); const account = (await registration.json()).account;
  t.after(async () => { try { await context.request.post(base + '/api/auth/login', { headers: { Origin: base }, data: { email, password } }); assert.equal((await context.request.delete(base + '/api/account', { headers: { Origin: base }, data: { password } })).status(), 200); } finally { await browser.close(); } });
  const page = await context.newPage(); const errors = []; page.on('pageerror', e => errors.push(e.message));
  let collectionsUnavailable = true;
  await page.route('**/api/collections', async route => {
    assert.equal((await route.request().allHeaders())['x-atlas-account'], account.id);
    if (collectionsUnavailable) return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: 'Unavailable' }) });
    await route.continue();
  });
  await page.route('**/api/plan', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: 'Unavailable' }) }));
  await page.goto(base + '/dashboard'); await page.getByRole('button', { name: 'Retry collections' }).waitFor();
  assert.equal(await page.locator('.sidebar-plan-title strong').textContent(), 'Your plan');
  assert.equal(await page.locator('.sidebar-plan-link').textContent(), 'View plan & usage');
  collectionsUnavailable = false; await page.getByRole('button', { name: 'Retry collections' }).click();
  await page.locator('.sidebar-collection-message').getByRole('link', { name: 'Create a collection' }).waitFor();
  await page.unroute('**/api/plan'); await page.route('**/api/plan', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ pro: true }) }));
  await page.reload(); await page.locator('.sidebar-plan-title strong', { hasText: 'Pro plan' }).waitFor();
  assert.equal(await page.locator('.sidebar-plan-link').textContent(), 'Manage plan');
  await page.setViewportSize({ width: 390, height: 844 }); await page.locator('#open-sidebar').click();
  await page.locator('#open-account').click(); await page.waitForURL(base + '/dashboard/settings');
  await page.waitForFunction(() => !document.querySelector('#main').inert);
  assert.equal(await page.locator('#open-sidebar').getAttribute('aria-expanded'), 'false');
  assert.equal(await page.locator('#sidebar-switch-account, #sidebar-account-menu').count(), 0);
  assert.equal((await context.request.get(base + '/api/me')).status(), 200, 'Opening settings keeps this session');
  assert.equal(await page.evaluate(() => document.body.style.overflow), '');
  assert.deepEqual(errors, []);
});
