import Link from 'next/link';
import {headers} from 'next/headers';
import type {Metadata} from 'next';
import {betaDistribution} from '../../lib/beta-distribution';
import {ThemeControl} from '../../components/appearance/theme';
import {CollectionIcon,collectionIcons} from '../../components/collections/public-chrome';
import '../customer.css';
import './beta.css';
export const metadata:Metadata={title:'Try FoundKeep · Beta access',robots:{index:false,follow:false}};
export default async function BetaPage(){
 const isDev=(await headers()).get('host')?.split(':')[0]==='dev.foundkeep.app',realm=isDev?'dev':'prod',origin=isDev?'https://dev.foundkeep.app':'https://foundkeep.app',distribution=betaDistribution[realm],appName=isDev?'FoundKeep Dev':'FoundKeep',extensionPath=isDev?'/ext/foundkeep-extension-dev.zip':'/foundkeep-extension.zip';
 return <div className="customer-body beta-page"><a className="skip-link" href="#main">Skip to content</a><header className="beta-header"><Link className="brand" href={origin}><img src="/assets/studio-mark.svg?v=bookmark-evolved-1" width={32} height={32} alt=""/><span>FoundKeep</span>{isDev?<small>Dev</small>:null}</Link><nav aria-label="Beta navigation"><ThemeControl compact/><Link href={origin+'/dashboard'}>Open my library<CollectionIcon>{collectionIcons.arrow}</CollectionIcon></Link></nav></header>
 <main id="main"><section className="beta-hero"><h1>{isDev?<>Your space<br/>to test what’s next.</>:<>Your good finds.<br/>Our next chapter.</>}</h1><p>{isDev?'Your private development environment, ready to try the next FoundKeep changes.':'Welcome to the FoundKeep friends beta. Save what catches your attention, connect the ideas, and tell us what could work better.'}</p><div className="beta-actions"><Link className="button" href={origin+'/signup'}>Create {isDev?'a dev':'your'} account<CollectionIcon>{collectionIcons.arrow}</CollectionIcon></Link><a href="#install">Choose your device</a></div><p className="beta-environment-note">{isDev?'Dev is for Pritam only. Friends use the production beta at foundkeep.app.':'This beta uses your real FoundKeep account and library. The mobile apps arrive through TestFlight or Android beta installation.'} Already joined? <Link href={origin+'/login'}>Sign in</Link>.</p></section>
 <section id="install" className="beta-install" aria-labelledby="beta-install-title"><div className="beta-section-heading"><h2 id="beta-install-title">One library, wherever you find it.</h2><p>Use the same {isDev?'dev ':''}account on every device.</p></div><div className="beta-install-grid">
 <article><div className="beta-install-icon"><CollectionIcon><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M7 6.5h.01M10 6.5h.01"/></CollectionIcon></div><span className="beta-device-label">Desktop · Chrome · Edge · Brave</span><h3>Use FoundKeep on your computer.</h3><p>{isDev?'Open your private dev dashboard, then add the dev extension. Its local library stays separate from your production extension.':'Open your production dashboard to browse and organize your library, then add the extension to save as you browse.'}</p><Link className="button" href={origin+'/dashboard'}>Open {isDev?'dev ':''}dashboard</Link><a className="text-link" href={origin+extensionPath} download>Download {isDev?'dev ':''}extension</a><details><summary>How to install the ZIP</summary><ol><li>Download and unzip the extension.</li><li>Open <code>chrome://extensions</code> and enable Developer mode.</li><li>Choose <strong>Load unpacked</strong> and select the unzipped extension folder.</li><li>Open <Link href={origin+'/dashboard/apps'}>Apps &amp; devices</Link>, then connect {appName}.</li><li>Pin the extension and save your first page.</li></ol></details></article>
 <article id="ios"><div className="beta-install-icon"><CollectionIcon><rect x="6" y="2" width="12" height="20" rx="3"/><path d="M10 5h4m-3 14h2"/></CollectionIcon></div><span className="beta-device-label">iPhone · iPad</span><h3>Keep it from the Share menu.</h3><p>Share a link, a photo, or a file into your library. Your original stays attached to the save.</p>{distribution.ios.url?<a className="button" href={distribution.ios.url}>Join on TestFlight</a>:<p className="beta-build-status">{distribution.ios.status}</p>}<p className="beta-small">After installing through TestFlight, open {appName} once and sign in. Then choose Share → {appName} in another app.</p></article>
 <article id="android"><div className="beta-install-icon"><CollectionIcon><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/></CollectionIcon></div><span className="beta-device-label">Android</span><h3>A place for finds on the go.</h3><p>{isDev?'The private dev Android build is not ready to install yet.':'Browse your library and add things from Android’s Share menu. This signed APK connects to foundkeep.app and uses your production account. A Play test is not available yet.'}</p>{distribution.android.playUrl?<a className="button" href={distribution.android.playUrl}>Join the Play test</a>:null}{distribution.android.apkUrl?<a className={distribution.android.playUrl?'text-link':'button'} href={distribution.android.apkUrl} download>Download Android APK</a>:<p className="beta-build-status">{distribution.android.status}</p>}{distribution.android.apkUrl?<><p className="beta-small">Version 1.0.0 (build 5) · 107.2 MB (107,242,309 bytes) · Android 7.0 or later.</p><details><summary>Install the APK</summary><ol><li>Download the APK on your Android phone and open the downloaded file.</li><li>If Android blocks the install, open the prompt’s settings and allow installs from your browser or Files app.</li><li>Return to the downloaded file and choose <strong>Install</strong>.</li><li>Open {appName} and sign in to your {isDev?'dev':'production'} FoundKeep account.</li><li>You can turn off that install permission after FoundKeep is installed.</li></ol></details></>:null}</article>
 </div></section>
 <section className="beta-tour" aria-labelledby="beta-tour-title"><div className="beta-section-heading"><h2 id="beta-tour-title">Follow something that interests you.</h2><p>Give it ten minutes. A small mix of saves is a good place to start.</p></div><ol><li><span>1</span><div><h3>Save a small mix.</h3><p>Try an article, a post, a YouTube link, an image, and a note. Open each save and check its source and content.</p></div></li><li><span>2</span><div><h3>Bring your own agent.</h3><p>Open <Link href={origin+'/dashboard/agents'}>Agent connections</Link>, enable “Add and organize saves,” and copy the private configuration into an HTTP MCP client. Free accounts can use this too.</p><blockquote>“Read my recent saves, add useful context, and link the ideas that belong together. Ask before making broad changes.”</blockquote></div></li><li><span>3</span><div><h3>See the connections.</h3><p>Open your <Link href={origin+'/dashboard/mind-map'}>Mind map</Link>. Follow tags and agent links, select a save, and return to the original.</p></div></li><li><span>4</span><div><h3>Make a collection worth sharing.</h3><p>Explore <Link href={origin+'/collections'}>public collections</Link>, then create your own. Keep it private or publish it, and choose who can contribute and whether suggestions need approval.</p></div></li></ol></section>
 <section className="beta-processing"><div><h2>Try Pro at your pace.</h2><p>Managed processing can suggest summaries, categories, tags, and related saves. It needs your consent and Pro access.{isDev?' Dev checkout uses Paddle’s sandbox.':''}</p><Link href={origin+'/dashboard/settings/processing'}>Open processing controls<CollectionIcon>{collectionIcons.arrow}</CollectionIcon></Link></div><ul><li><strong>As I save</strong><span>Process each new save.</span></li><li><strong>On a schedule</strong><span>Batch new saves every 1, 6, or 24 hours.</span></li><li><strong>Only when I ask</strong><span>Choose individual items to process.</span></li><li><strong>Paused</strong><span>Keep saving without processing usage.</span></li></ul><p className="beta-processing-note">Set a monthly credit cap. Failed or cancelled jobs do not spend a credit. Public links may expose only a preview; protected posts and missing video transcripts are marked as such.</p></section>
 <section className="beta-feedback"><h2>The rough edges are useful feedback.</h2><p>Tell us what you tried, what you expected, and what happened. Include your browser or device and app version. Keep passwords, connection tokens, and private saves out of the report.</p><a className="button" href={`mailto:notpritamsharma@gmail.com?subject=FoundKeep%20${isDev?'Dev%20':''}beta%20feedback&body=Device%20and%20version%3A%0A%0AWhat%20I%20tried%3A%0A%0AWhat%20I%20expected%3A%0A%0AWhat%20happened%3A%0A`}>Send beta feedback<CollectionIcon>{collectionIcons.arrow}</CollectionIcon></a><Link href={origin+'/support'}>Get help</Link></section>
 </main><footer className="beta-footer"><span>FoundKeep · {isDev?'Private dev':'Friends beta'}</span><Link href={origin+'/privacy'}>Privacy &amp; your data</Link></footer></div>;
}
