import type {Metadata,Viewport} from 'next';
import type {ReactNode} from 'react';
import './global.css';
import './appearance.css';
import Script from 'next/script';
import {ThemeProvider} from '../components/appearance/theme';
export const metadata:Metadata={metadataBase:new URL('https://foundkeep.app'),title:{default:'Foundkeep — A place for the things worth keeping',template:'%s — Foundkeep'},description:'Keep links, highlights, photos and files in one private collection. Save from your browser, iPhone or the web.',icons:{icon:'/assets/studio-mark.svg?v=bookmark-evolved-1',apple:[{url:'/assets/apple-touch-icon.png?v=bookmark-evolved-1',sizes:'180x180',type:'image/png'}]},openGraph:{type:'website',siteName:'Foundkeep',images:[{url:'/assets/foundkeep-scenic-social.png',width:1200,height:630}]},twitter:{card:'summary_large_image'}};
export const viewport:Viewport={width:'device-width',initialScale:1,themeColor:[{media:'(prefers-color-scheme: light)',color:'#f5fafc'},{media:'(prefers-color-scheme: dark)',color:'#16191d'}]};
export default function RootLayout({children}:{children:ReactNode}){return <html lang="en" suppressHydrationWarning><head><Script id="foundkeep-appearance" strategy="beforeInteractive" dangerouslySetInnerHTML={{__html:`(()=>{let p='system';try{const s=localStorage.getItem('foundkeep.appearance');if(['light','dark','system'].includes(s))p=s}catch{}const t=p==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):p,c=t==='dark'?'#16191d':'#f5fafc',m=()=>document.querySelectorAll('meta[name="theme-color"]').forEach(e=>e.content=c);document.documentElement.dataset.theme=t;document.documentElement.style.colorScheme=t;document.readyState==='loading'?document.addEventListener('DOMContentLoaded',m,{once:true}):m()})()`}}/><link rel="preload" href="/assets/fonts/geist-latin.woff2" as="font" type="font/woff2" crossOrigin="anonymous"/><link rel="preload" href="/assets/fonts/ClarityCity-Medium.woff2" as="font" type="font/woff2" crossOrigin="anonymous"/></head><body><ThemeProvider>{children}</ThemeProvider></body></html>;}
