import {CUSTOMER_ORIGIN} from './product.js';

// Explicit sharing is separate from the local capture/outbox: opening this form
// never uploads a private annotation, article, image, or account credential.
export function bindCollections(container,{getAccountId,getSource}) {
 if(!container)return {reset(){}};
 const suffix=container.id||'shared';
 container.innerHTML=`<details class="shared-collection-picker"><summary>Add to a collection</summary><form><p class="fine">Share a link or selected text with a collection. Your private library stays separate.</p><label for="${suffix}-target">Collection</label><select id="${suffix}-target" required><option value="">Choose a collection</option></select><p class="fine" data-rules></p><label for="${suffix}-title">Title</label><input id="${suffix}-title" maxlength="200" required><label for="${suffix}-url">Source link (optional)</label><input id="${suffix}-url" type="url" maxlength="2048"><label for="${suffix}-body">Description or quote (optional)</label><textarea id="${suffix}-body" rows="3" maxlength="5000" placeholder="Write only what you want to share."></textarea><label data-image-label hidden><input type="checkbox" data-image> Include the saved image</label><p class="statusline" data-feedback role="status"></p><div class="shared-collection-actions"><button class="btn primary" type="submit" disabled>Add to collection</button><a data-manage target="_blank" rel="noopener noreferrer">Manage collections</a></div></form></details>`;
 const details=container.querySelector('details'),form=container.querySelector('form'),select=container.querySelector('select'),title=container.querySelector('#'+suffix+'-title'),url=container.querySelector('#'+suffix+'-url'),body=container.querySelector('textarea'),button=container.querySelector('button'),feedback=container.querySelector('[data-feedback]'),rules=container.querySelector('[data-rules]'),image=container.querySelector('[data-image]');
 container.querySelector('[data-manage]').href=CUSTOMER_ORIGIN+'/dashboard/collections';
 let epoch=0,owner=null,source=null,collections=[],clientId=null,busy=false;
 const say=(value,error=false)=>{feedback.textContent=value;feedback.dataset.state=error?'error':'success';};
 async function request(operation,args={}) {const accountId=getAccountId();if(!accountId||accountId!==owner)throw new Error('Connect your account and reopen collection sharing.');const response=await chrome.runtime.sendMessage({kind:'library-request',operation,args,accountId});if(accountId!==getAccountId()||owner!==accountId)throw new Error('Your connected account changed. Reopen collection sharing.');if(!response?.ok)throw new Error(response?.error||'Could not reach your collections.');return response.data;}
 function selected(){return collections.find(c=>c.id===select.value);}
 function selection(){const c=selected();clientId=null;button.disabled=busy||!c;const pending=c?.requireApproval&&!c?.canModerate;button.textContent=pending?'Submit for approval':'Add to collection';rules.textContent=c?`${c.visibility==='public'?'Public: anyone can read approved entries.':'Private: only accepted members can read.'} ${pending?'The owner must approve your submission.':'Your entry appears immediately.'}${c.rules?' Rules: '+c.rules:''}`:'';say('');}
 async function load(){const serial=++epoch;owner=getAccountId();source=null;collections=[];button.disabled=true;form.reset();select.replaceChildren(new Option('Loading collections…',''));say('');try{if(!owner)throw new Error('Connect your Foundkeep account to add to a collection.');const [result,current]=await Promise.all([request('collections'),getSource()]);if(serial!==epoch)return;if(owner!==getAccountId())throw new Error('Your account changed. Reopen collection sharing.');source=current||{};title.value=String(source.sourceTitle||source.title||'').slice(0,200);url.value=source.sourceUrl||source.url||'';body.value='';container.querySelector('[data-image-label]').hidden=!source.blobUrl;collections=(result.collections||[]).filter(c=>c.canSubmit);select.replaceChildren(new Option('Choose a collection',''));for(const c of collections)select.add(new Option(`${c.title} · ${c.visibility}`,c.id));if(!collections.length)say('Create a collection, join a group, or follow a public collection that accepts contributions.');}catch(e){if(serial===epoch)say(e.message,true);}}
 details.addEventListener('toggle',()=>{if(details.open)void load();else{epoch++;button.disabled=true;}});
 select.onchange=selection;form.oninput=()=>{clientId=null;say('');};
 form.onsubmit=async event=>{event.preventDefault();const target=selected();if(busy||!target)return;const serial=epoch;busy=true;button.disabled=true;say('');clientId||=crypto.randomUUID();try{const result=await request('submit-collection',{id:target.id,value:{clientId,title:title.value.trim(),url:url.value.trim(),body:body.value.trim(),tags:[],...(source?.id?{captureId:source.id}:{}),shareImage:!container.querySelector('[data-image-label]').hidden&&image.checked}});if(serial!==epoch)return;say(result.entry?.status==='pending'?'Submitted. It will appear after approval.':'Added to the collection.');clientId=null;body.value='';}catch(e){if(serial===epoch)say(e.message,true);}finally{busy=false;if(serial===epoch)button.disabled=!selected();}};
 return {reset(){epoch++;owner=null;source=null;collections=[];details.open=false;form.reset();button.disabled=true;say('');}};
}
