'use client';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {useDashboard} from './context';
import {ThemeControl} from '../appearance/theme';
import {SectionLoading,RefreshIcon,Spinner} from './loading';
import type {MindMapData,MindMapNode} from '../../lib/mind-map';
import './mind-map.css';
const Canvas=dynamic(()=>import('./mind-map-canvas'),{ssr:false,loading:()=> <SectionLoading label="Opening the interactive map…"/>});
export default function MindMap(){
 const {me,request}=useDashboard();
 const [input,setInput]=useState(''),[query,setQuery]=useState(''),[focus,setFocus]=useState(''),[view,setView]=useState<'graph'|'list'>('graph'),[showTags,setShowTags]=useState(true),[selected,setSelected]=useState<string|null>(null);
 const graph=useQuery({queryKey:['mind-map',me.account.id,query,focus],queryFn:({signal})=>request<MindMapData>('/graph?'+new URLSearchParams({q:query,...(focus?{focus}:{})}),{signal}),refetchInterval:15_000,refetchIntervalInBackground:false});
 const data=graph.data,current=data?.nodes.find(node=>node.id===selected),saves=data?.nodes.filter(node=>node.kind==='save')||[];
 const linked=current?data?.edges.filter(edge=>edge.source===current.id||edge.target===current.id).map(edge=>({node:data.nodes.find(node=>node.id===(edge.source===current.id?edge.target:edge.source)),label:edge.label})).filter((item):item is {node:MindMapNode;label:string}=>Boolean(item.node)):[];
 const clear=()=>{setInput('');setQuery('');setFocus('');setSelected(null);};
 return <div className="mind-map-page"><header className="mind-map-heading"><div><h1>Mind map</h1><p>Your saves, connected.</p></div><ThemeControl compact/></header>
  <div className="mind-map-toolbar"><form onSubmit={event=>{event.preventDefault();setQuery(input.trim());setSelected(null);}}><label className="sr-only" htmlFor="mind-map-search">Search your mind map</label><input id="mind-map-search" type="search" maxLength={100} placeholder="Find a save, topic, or idea…" value={input} onChange={event=>setInput(event.target.value)}/><button className="button secondary" type="submit">Search</button></form><div className="mind-map-view" role="group" aria-label="Mind map view"><button type="button" aria-pressed={view==='graph'} onClick={()=>setView('graph')}>Map view</button><button type="button" aria-pressed={view==='list'} onClick={()=>setView('list')}>List view</button></div><button className="mind-map-refresh" type="button" aria-label="Refresh mind map" title="Refresh mind map" disabled={graph.isFetching} onClick={()=>void graph.refetch()}>{graph.isFetching?<Spinner/>:<RefreshIcon active={false}/>}</button></div>
  {data?<div className="mind-map-summary"><p>{focus?'Focused connections':query?`Results for “${query}”`:'Your collection, connected'}<span>{data.shownSaves} of {data.matchingSaves} saves{data.truncated?' · Showing the most recent matches. Search to find older saves.':''}{data.totalTags>data.shownTags?` · ${data.shownTags} most-used tags shown`:''}</span></p><div>{query||focus?<button className="subtle-button" onClick={clear}>Show all saves</button>:null}<label><input type="checkbox" checked={showTags} onChange={event=>{setShowTags(event.target.checked);setSelected(null);}}/>Show tags</label></div></div>:null}
  {graph.isError?<div className="mind-map-error" role="alert"><p>{graph.error.message}</p><button className="button secondary" onClick={()=>void graph.refetch()}>Retry map</button></div>:null}
  {graph.isPending?<SectionLoading label="Finding your connections…"/>:data&&!saves.length?<section className="mind-map-empty"><h2>{query||focus?'No saves match yet.':'Your next connection starts with a save.'}</h2><p>{query||focus?'Try another word or open your full mind map.':'Save a link or note, add tags, or connect your agent to start building a map of your ideas.'}</p><div>{query||focus?<button className="button secondary" onClick={clear}>Show all saves</button>:<><Link className="button primary" href="/dashboard">Open my library</Link><Link className="button secondary" href="/dashboard/agents">Connect an agent</Link></>}</div></section>:data?<>
   <div className="mind-map-content" data-inspecting={Boolean(current)}><section aria-label={view==='graph'?'Your connections':'Saved items in your map'} className="mind-map-visual">{view==='graph'?<Canvas data={data} showTags={showTags} selected={selected} onSelect={setSelected}/>:<ul className="mind-map-list">{saves.map(node=><li key={node.id}><button type="button" aria-label={'Inspect '+node.label} aria-pressed={selected===node.id} onClick={()=>setSelected(node.id)}><span>{node.type}</span><strong>{node.label}</strong><small>{node.tags?.length?node.tags.join(' · '):'No tags yet'}</small></button></li>)}</ul>}<div className="mind-map-legend" aria-label="Connection types"><span className="legend-save">Saves</span><span className="legend-agent">Agent links</span><span className="legend-hosted">Processing suggestions</span>{showTags?<span className="legend-tag">Shared tags</span>:null}</div></section>
    <aside className="mind-map-inspector" aria-label="Selected connection" hidden={!current}>{current?<><div className="mind-map-inspector-top"><span>{current.kind==='tag'?'Topic':current.type||'Saved item'}</span><button className="subtle-button" onClick={()=>setSelected(null)}>Clear selection</button></div><h2>{current.label}</h2>{current.summary?<p>{current.summary}</p>:null}{current.kind==='save'?<><div className="mind-map-tags">{current.tags?.map(tag=><span key={tag}>{tag}</span>)}</div><Link className="button primary" href={'/dashboard/saved/'+current.saveId}>Open saved item</Link><button className="subtle-button" onClick={()=>{setFocus(current.saveId||'');setQuery('');setInput('');}}>Focus its connections</button>{current.sourceUrl?<a className="mind-map-source" href={current.sourceUrl} target="_blank" rel="noopener noreferrer">Visit original source ↗</a>:null}</>:null}<h3>Connected here</h3>{linked?.length?<ul className="mind-map-related">{linked.map((item,index)=><li key={item.node.id+index}><button type="button" onClick={()=>setSelected(item.node.id)}><span>{item.label}</span><strong>{item.node.label}</strong></button></li>)}</ul>:<p>No visible connections yet. Your agent can use link_saves to attach a related item.</p>}</>:<><span>Follow an idea</span><h2>A little context goes a long way.</h2><p>Select a save or tag to see what connects to it. Open the original, explore a related idea, or focus one part of your library.</p><div className="mind-map-agent-note"><h3>Let your agent help</h3><p>Ask it to read your recent saves, add useful context, and connect related ideas. Those links appear here.</p><Link href="/dashboard/agents">Connect your agent →</Link></div><p className="mind-map-private-note">This map belongs to your private library. Public collections only contain what you deliberately share.</p></>}</aside>
   </div></>:null}
 </div>;
}
